### ISSUE TITLE
I got java.lang.NoClassDefFoundError: com/typesafe/scalalogging/Logger$ when I ran databrick notebook

### ISSUE THREAD

**Issue by AlberTadrous** [SANSA-Stack/SANSA-Notebooks#18]
Every time I run this snippet of code on databricks notebook: 
**import net.sansa_stack.owl.spark.dataset.FunctionalSyntaxOWLAxiomsDatasetBuilder
val input = "hdfs://namenode:8020/data/ont_functional.owl"
val dataset = FunctionalSyntaxOWLAxiomsDatasetBuilder.build(spark, input)
dataset.take(10).foreach(println(_))**

I got this exception "java.lang.NoClassDefFoundError: com/typesafe/scalalogging/Logger$"
at net.sansa_stack.owl.common.parsing.FunctionalSyntaxParsing$class.$init$(FunctionalSyntaxParsing.scala:30)
	at net.sansa_stack.owl.spark.dataset.FunctionalSyntaxOWLAxiomsDatasetBuilder$.<init>(FunctionalSyntaxOWLAxiomsDatasetBuilder.scala:8)
	at net.sansa_stack.owl.spark.dataset.FunctionalSyntaxOWLAxiomsDatasetBuilder$.<clinit>(FunctionalSyntaxOWLAxiomsDatasetBuilder.scala)
	at line187486337eb042669b66dc9b3267112b31.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2529293180297734:4)
	at line187486337eb042669b66dc9b3267112b31.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-2529293180297734:56)
	at line187486337eb042669b66dc9b3267112b31.$read$$iw$$iw$$iw$$iw.<init>(command-2529293180297734:58)
	at line187486337eb042669b66dc9b3267112b31.$read$$iw$$iw$$iw.<init>(command-2529293180297734:60)
	at line187486337eb042669b66dc9b3267112b31.$read$$iw$$iw.<init>(command-2529293180297734:62)
	at line187486337eb042669b66dc9b3267112b31.$read$$iw.<init>(command-2529293180297734:64)
	at line187486337eb042669b66dc9b3267112b31.$read.<init>(command-2529293180297734:66)
	at line187486337eb042669b66dc9b3267112b31.$read$.<init>(command-2529293180297734:70)
	at line187486337eb042669b66dc9b3267112b31.$read$.<clinit>(command-2529293180297734)
	at line187486337eb042669b66dc9b3267112b31.$eval$.$print$lzycompute(<notebook>:7)
	at line187486337eb042669b66dc9b3267112b31.$eval$.$print(<notebook>:6)
	at line187486337eb042669b66dc9b3267112b31.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:215)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply$mcV$sp(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:694)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:647)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$9.apply(DriverLocal.scala:381)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$9.apply(DriverLocal.scala:358)
	at com.databricks.logging.UsageLogging$$anonfun$withAttributionContext$1.apply(UsageLogging.scala:235)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at com.databricks.logging.UsageLogging$class.withAttributionContext(UsageLogging.scala:230)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:49)
	at com.databricks.logging.UsageLogging$class.withAttributionTags(UsageLogging.scala:272)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:49)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:358)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:644)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:644)
	at scala.util.Try$.apply(Try.scala:192)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:639)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:485)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:597)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:390)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:337)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:219)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.typesafe.scalalogging.Logger$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.databricks.backend.daemon.driver.ClassLoaders$LibraryClassLoader.loadClass(ClassLoaders.scala:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.sansa_stack.owl.common.parsing.FunctionalSyntaxParsing$class.$init$(FunctionalSyntaxParsing.scala:30)
	at net.sansa_stack.owl.spark.dataset.FunctionalSyntaxOWLAxiomsDatasetBuilder$.<init>(FunctionalSyntaxOWLAxiomsDatasetBuilder.scala:8)
	at net.sansa_stack.owl.spark.dataset.FunctionalSyntaxOWLAxiomsDatasetBuilder$.<clinit>(FunctionalSyntaxOWLAxiomsDatasetBuilder.scala)
	at line187486337eb042669b66dc9b3267112b31.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2529293180297734:4)
	at line187486337eb042669b66dc9b3267112b31.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-2529293180297734:56)
	at line187486337eb042669b66dc9b3267112b31.$read$$iw$$iw$$iw$$iw.<init>(command-2529293180297734:58)
	at line187486337eb042669b66dc9b3267112b31.$read$$iw$$iw$$iw.<init>(command-2529293180297734:60)
	at line187486337eb042669b66dc9b3267112b31.$read$$iw$$iw.<init>(command-2529293180297734:62)
	at line187486337eb042669b66dc9b3267112b31.$read$$iw.<init>(command-2529293180297734:64)
	at line187486337eb042669b66dc9b3267112b31.$read.<init>(command-2529293180297734:66)
	at line187486337eb042669b66dc9b3267112b31.$read$.<init>(command-2529293180297734:70)
	at line187486337eb042669b66dc9b3267112b31.$read$.<clinit>(command-2529293180297734)
	at line187486337eb042669b66dc9b3267112b31.$eval$.$print$lzycompute(<notebook>:7)
	at line187486337eb042669b66dc9b3267112b31.$eval$.$print(<notebook>:6)
	at line187486337eb042669b66dc9b3267112b31.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:215)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply$mcV$sp(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:694)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:647)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$9.apply(DriverLocal.scala:381)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$9.apply(DriverLocal.scala:358)
	at com.databricks.logging.UsageLogging$$anonfun$withAttributionContext$1.apply(UsageLogging.scala:235)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at com.databricks.logging.UsageLogging$class.withAttributionContext(UsageLogging.scala:230)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:49)
	at com.databricks.logging.UsageLogging$class.withAttributionTags(UsageLogging.scala:272)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:49)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:358)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:644)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:644)
	at scala.util.Try$.apply(Try.scala:192)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:639)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:485)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:597)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:390)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:337)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:219)
	at java.lang.Thread.run(Thread.java:748)

**Comment by JensLehmann** [comment]
We will investigate Databricks support for the SANSA 0.9 release. Currently, we do not have the resources and man power to support / investigate Databricks notebook (especially potential versioning conflicts) support even though we believe it would be interesting for SANSA.
