### ISSUE TITLE
Running examples using SANSA Notebook

### ISSUE THREAD

**Issue by HajiraJabeen** [SANSA-Stack/SANSA-Notebooks#2]
While the sign 'finished' appears on the right side of each example, 
when I click the 'play' sign in front of any example e.g. sparkpi, 
it gives the following error : ( Tested on Docker engine version:  17.09.0 )

paragraph_1494446151737_1359394047's Interpreter null not found
org.apache.zeppelin.interpreter.InterpreterException: paragraph_1494446151737_1359394047's Interpreter null not found
	at org.apache.zeppelin.notebook.Note.run(Note.java:605)
	at org.apache.zeppelin.socket.NotebookServer.persistAndExecuteSingleParagraph(NotebookServer.java:1641)
	at org.apache.zeppelin.socket.NotebookServer.runParagraph(NotebookServer.java:1615)
	at org.apache.zeppelin.socket.NotebookServer.onMessage(NotebookServer.java:265)
	at org.apache.zeppelin.socket.NotebookSocket.onWebSocketText(NotebookSocket.java:59)
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:128)
	at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:65)
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:122)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:161)
	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:309)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:214)
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:258)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:632)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:480)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

**Comment by HajiraJabeen** [comment]
While trying CLI examples inn the same installation I get :
****
.
.

triples-reader_1                 | /submit.sh: line 5: /wait-for-step.sh: Permission denied
triples-reader_1                 | Submit application /jars/sansa-examples-spark.jar with main class net.sansa_stack.examples.spark.rdf.TripleReader to Spark master spark://spark-master:7077
triples-reader_1                 | Passing arguments hdfs://namenode:8020/data/rdf.nt
triples-reader_1                 | /submit.sh: line 10: /execute-step.sh: Permission denied
triples-reader_1                 | ======================================
triples-reader_1                 | |        Triple reader example       |
triples-reader_1                 | ======================================
triples-reader_1                 | 17/11/18 23:35:43 INFO spark.SparkContext: Running Spark version 2.1.2-SNAPSHOT
triples-reader_1                 | 17/11/18 23:35:43 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
.
.triples-reader_1                 | /submit.sh: line 15: /finish-step.sh: Permission denied

**Comment by GezimSejdiu** [comment]
Hi @HajiraJabeen ,
for some reason the interpreter is not set up properly when you start the Notebook (which was created before), you may need to restart it (only the interpreter - in our case Spark). Could you please do it (i.e have a look [here](https://youtu.be/aHCoWmzUJlE?t=5m27s) how to do it) and let me know if that is working fine for you. 
I just tested SparkPi example and it works just fine.
![sparkpi](https://user-images.githubusercontent.com/5259296/33014964-5abdc432-cde9-11e7-968b-7a90b127f30e.png)

_Reg. the second issue, maybe you could open a different issue for that (since we have to see how to setup the sudo permission for the running notebooks)._

Best,

**Comment by shatestest** [comment]
@GezimSejdiu  will be grateful for any help on this issue 

https://stackoverflow.com/questions/54312233/zeppeling-throwing-nullpointerexception-while-configuring
