### ISSUE TITLE
HUE throws an error and does not work with docker on macOS

### ISSUE THREAD

**Issue by sheldonkhall** [SANSA-Stack/SANSA-Notebooks#3]
I just followed the instructions in the README to get the stack installed on docker and run the examples. I am using macOS 10.12.6 and docker 17.09.0-ce-mac35. The commands:
`make`
`make up`
`make load-data`
appear to work fine. However when I go to the HUE endpoint http://localhost:8088/ I get this traceback:
```
Traceback (most recent call last)
File "/opt/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/contrib/staticfiles/handlers.py", line 67, in __call__
return self.application(environ, start_response)
File "/opt/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/wsgi.py", line 206, in __call__
response = self.get_response(request)
File "/opt/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/base.py", line 194, in get_response
response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
File "/opt/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/base.py", line 229, in handle_uncaught_exception
return debug.technical_500_response(request, *exc_info)
File "/opt/hue/build/env/lib/python2.7/site-packages/django_extensions-1.5.0-py2.7.egg/django_extensions/management/technical_response.py", line 5, in null_technical_500_response
six.reraise(exc_type, exc_value, tb)
File "/opt/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/base.py", line 112, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/transaction.py", line 371, in inner
return func(*args, **kwargs)
File "/opt/hue/desktop/core/src/desktop/views.py", line 304, in index
return redirect(reverse('about:index'))
File "/opt/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/urlresolvers.py", line 532, in reverse
key)
NoReverseMatch: u'about' is not a registered namespace
```

I will have a look at resolving it, do you have any ideas?

**Comment by GezimSejdiu** [comment]
Hi @sheldonkhall ,
many thanks for using the SANSA-Notebooks. This issue is a well-known issue from Hue and we solve it by going to http://localhost:8088/home . 

Could you try and let us know.

Best,

**Comment by sheldonkhall** [comment]
Hey thanks for the fast reply! That url worked for me. In the meantime I submitted a PR to fix the docs because this was where I was caught out.

**Comment by GezimSejdiu** [comment]
Hi @sheldonkhall ,
great! Shall we consider this issue as a closed one?
Many thanks for your valuable feedback.

Best
